# Presente neste arquivo, há configurações do fuzzel prediletas ao repositor.
# Em caso de de acordo opinativo de funcionalidades, recomenda-se a consulta via "man".
# =====================
# I. Básico ("main")
# =====================
### I.I. Fonte padrão
font=JetBrains Mono:size=14
### I.II. Desabilita redimencionamento de fontes pelo DPI do monitor em uso
dpi-aware=no
### I.III. Texto exibido no espaço da caixa de entrada 
placeholder=⠀---------------------
### I.IV. Desativa amostra de ícones
icons-enabled=no
### I.V. Lista das entradas XDG Desktop
fields=filename,name,generic
### I.VI. Define o mode de correspondência à caixa de entrada
match-mode=fzf
### I.VII. Mostra a contagem de correspondentes e totais
match-counter=yes
## II. Posicionamento
### II.I. Âncora a janela numa posição
anchor=center
### II.II. Quantidade de correspondências a serem mostradas
lines=7
### II.III. Largura da janela
width=30
### II.IV. Distância horizontal do espaçamento interno
horizontal-pad=2
### II.V. Distância vertical do espaçamento
vertical-pad=1
### II.VI. Distância dos elementos internos
inner-pad=2
# =====================
# II. Estética
# =====================
[colors]
## I. Cores
### I.I. Fundo
background=282828ff
### I.II Texto
text=ebdbb2ff
### I.III. Ícone/Texto do prompt
prompt=282828ff
### I.IV. Texto de ajuda/placeholder
placeholder=928374f
### I.V. Texto digitado no campo de busca
input=ebdbb2ff
### I.VI. Letras correspondentes à busca
match=fabd2fff
### I.VII. Fundo do item selecionado
selection=fbf1c7ff
### I.VIII. Texto do item selecionado
selection-text=282828ff
### I.IX. Destaque de busca na seleção
selection-match=d79921ff
### I.X. Contador de resultados
counter=ebdbb2ff
### I.XI. Borda externa
border=504945ff
## II. Bordas
[border]
### II.I. Tamanho da borda 
width=1.5
### II.II. Arredondamento dos cantos
radius=5
# --- FIM ---
