# Configuração pessoal do foot
# =====================
# I. Básico ("main")
# =====================
### I. Define o "shell" padrão. Ex.: bash, zsh etc. ("$SHELL" é recomendado) 
shell=/bin/bash
### II. Informa à aplicações o terminfo
term=foot
### III. Diz ao foot para abrir como shell interativo comum (carrega o ~/.bashrc) 
login-shell=no
### IV. Identificado para o compositor de janelas
app-id=foot
### V. Identificação aparente em gerenciadores de janela. Ex.: foot na barra de título do waybar
title=foot
### VI. Permite alteração de título dinamicamente para aplicações
locked-title=no
## VII. Fontes
### VII.I. Define a fonte e tamanho de fonte
font=JetBrains Mono:size=14
### VII.II. Define aumento ou decréscimo de tamanho de fonte em atalhos de "zoom"
font-size-adjustment=0.5 
### VII.III. Define a altura das linhas
line-height=14
### VII.IV. Delega a renderização das fontes para o compositor 
dpi-aware=no
## VIII. Janela e espaçamento
### VIII.I. Deixe em "windowed" para o foot não entrar em conflito com os atalhos do sway
initial-window-mode=windowed
### VIII.II. Define o espaçamento entre janela e texto
pad=8x8 center
### VIII.II. Define a altura das linhas
line-height=18
## IX. Mouse
### IX.I. Caracteres que funcionam como separadores de palavras no duplo clique
word-delimiters=,│`|:"'()[]{}<>
### IX.II. Envia a seleção do mouse tanto para o Ctrl+V quanto para o botão do meio
selection-target=both
# =====================
# II. Segurança
# =====================
[security]
### I. Permite acesso à área de transferênvia via OSC-52
osc52=enabled
# =====================
# III. Notificação
# =====================
[bell]
### I. Emite sinal para o gerenciador de janelas definir janela/aba como urgente
urgent=yes
### II. Permite alerta visual sem emissão sonora
visual=yes
# =====================
# IV. Aparência
# =====================
[cursor]
## I. Configurações do cursor
### I.I. Define a forma do cursor 
style=block
### I.II. Define cor do cursor e texto sob ele
color=fb4934 ebdbb2
### I.III. Cursor intermitente 
blink=yes
### I.IV. Frequência de intermitência 
blink-rate=500
## II. Configurações de mouse
[mouse]
### II.I. Ponteiro do mouse some quando você digita
hide-when-typing=yes
### II.II. Desativa movimentação de página com a esfera central ("scroll") do mouse 
alternate-scroll-mode=no
## III. Cores do terminal
[colors]
### As cores utilizadas baseiam-se no padrão denominada comumente "Gruvbox Dark"
### As cores utilizadas baseiam-se no padrão denominado comumente "Gruvbox Dark"
### III.I. Fundo escuro terroso
background=282828
### III.II. Texto creme suave
foreground=ebdbb2
### III.III. Cores comuns
### III.III.I. Preto (fundo)
regular0=282828
### III.III.II. Vermelho suave
regular1=cc241d
### III.III.III. Verde suave
regular2=98971a
### III.III.IV. Amarelo opaco
regular3=d79921
### III.III.V. Azul suave
regular4=458588
### III.III.VI. Magenta
regular5=b16286
### III.III.VII. Ciano
regular6=689d6a
### III.III.VIII. Cinza
regular7=a89984
### III.IV. Cores brilhantes
### III.IV.I. Cinza escuro (Preto brilhante)
bright0=928374
### III.IV.II. Vermelho brilhante
bright1=fb4934
### III.IV.III. Verde brilhante
bright2=b8bb26
### III.IV.IV. Amarelo brilhante
bright3=fabd2f
### III.IV.V. Azul brilhante
bright4=83a598
### III.IV.VI. Magenta brilhante
bright5=d3869b
### III.IV.VII. Ciano brilhante
bright6=8ec07c
### III.IV.VIII. Creme claro (Branco brilhante)
bright7=ebdbb2
### III.V. Cores diversas
### III.V.I. Texto e fundo da seleção de texto com o mouse
selection-foreground=fe8019
selection-background=282828
### III.V.II. Rótulos de navegação e atalhos rápidos
jump-labels=282828 fabd2f
### III.V.III. Indicador visual da posição de rolagem do histórico
scrollback-indicator=282828 83a598
### III.V.IV. Destaque na caixa de busca quando não há correspondência
search-box-no-match=282828 fb4934
### III.V.V. Destaque na caixa de busca para termos encontrados
search-box-match=282828 fabd2f
### III.V.VI. Cor de realce aplicada a links e URLs
urls=83a598
### III.VI. Cor do alerta visual
flash=1d2021
# --- FIM ---
